spring.application.name=digigram_backend
server.port=8080


spring:main:
allow-bean-definition-overriding: true
firebase.config=classpath:firebase-service-account.json
GEMINI_API_KEY=AIzaSyDYxCw3qR6bPb-IzWsB1JKx_gNrUgE3k5o
OPENROUTER_API_KEY=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

spring.mvc.dispatch-options-request=true
spring.main.web-application-type=servlet
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
